config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do 
    authenticated :user do 
      root 'groups#index', as: :authenticated_root
    end
    unauthenticated :user do 
      root 'splash#index', as: :unauthenticated_root
    end
  end
  # Defines the root path route ("/")
  # root 'users#splash'

  resources :users, only: [:splash]
  resources :groups, only: [:index, :new, :create, :edit, :update, :destroy], :path => "categories" do
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy], :path => "transactions"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, length: { in: 1..50 },
                   uniqueness: { scope: :author, message: 'You already have a transaction with this name' }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 1..15 },
                   uniqueness: { scope: :author, message: 'You already have a category with this name' }
  # validates : presence: true, length: { in: 1..150 }

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy

  def total_expenses
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :groups, foreign_key: 'author_id'
  has_many :expenses, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def after_sign_up_path_for(_resource)
    users_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_group, only: %i[index new edit create update destroy]

  def index
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def new
    @expense = Expense.new
  end

  def create
    @author = current_user
    @expense = @author.expenses.new expense_params
    if @expense.save
      @group_expense = GroupExpense.create(group: @group, expense: @expense)
      redirect_to group_expenses_path(@group.id), notice: 'Transaction was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @groups = Group.all.order(name: :asc)
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @category = Group.find((params[:expense][:category])[1])
    @expense = @group.expenses.find(params[:id])
    @group_expense = GroupExpense.where(group: @group, expense: @expense)
    if @expense.update(expense_params)
      @group_expense.update(group: @category, expense: @expense)
      redirect_to group_expenses_url(@group), notice: 'Transaction was successfully updated.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @group = Group.find(params[:group_id])
    if @expense.destroy
      flash[:success] = 'Transaction was successfully removed.'
    else
      flash[:error] = 'Transaction could not be removed'
    end
    redirect_to group_expenses_url(@group)
  end

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.includes(:group_expenses).where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_url, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_url, notice: 'Category was successfully updated.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.expenses.empty?
      if @group.destroy
        flash[:success] = 'Category was successfully removed.'
      else
        flash[:error] = 'Error: Category could not be removed'
      end
    else
      flash[:error] = 'Error: Category with expense can not be deleted.'
    end
    redirect_to groups_url
  end

  private

  def group_params
    params.require(:group).permit(:author_id, :name)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def splash
    if current_user
      redirect_to groups_url, alert: "You are already logged in as, #{current_user.name}"
    else
      render :splash
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<div class="mb-3">
  <%= form.label :name, class: "form-label" %><br />
  <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
</div>
<div class="mb-3">
  <%= form.label :amount, class: "form-label" %><br />
  <%= form.number_field :amount, autofocus: true, autocomplete: "amount", class: "form-control" %>
</div>
<div class="mb-3">
  <%= form.label :category, class: "form-label" %><br />
  <%= form.select :category, Group.includes(:group_expenses).where(author_id: current_user.id).order(created_at: :desc).order(name: :asc).map {|category| [ category.name, category.id ] }, {}, class: "form-select", multiple: "multiple" %>
</div>

app/views/expenses/edit.html.erb
<%= render 'shared/banner', name: "Edit #{@group.name} Transaction - #{@expense.name}", amount: nil%>
<% if @expense.errors.any? %>
  <div class="alert alert-danger p-3">
    <h6><%= pluralize(@expense.errors.count, "error") %> prohibited this post from being saved:</h6>

    <ul>
    <% @expense.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="card m-3">
  <div class="card-body">
    <%= form_with model: @expense, url: group_expense_path(@group, @expense), class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
      <%= render 'expenses/form', form: form%>
      <div class="actions">
        <%= form.submit "Update", class: "btn btn-success w-100 mt-2" %>
      </div>
    <%end%>
  </div>
</div>

app/views/expenses/index.html.erb
<%= render 'shared/banner', name: "#{@group.name}' Transactions", amount: @group.total_expenses%>
<% if @expenses.empty? %>
  <h6 class="p-5 text-danger">There is no Transaction for this category</h6>
<% end %>
<% @expenses.each do |expense| %>
    <div class="d-flex justify-content-between align-items-center text-center m-3 p-3 item-container">
      <div class="d-flex justify-content-between align-items-center w-100">
        <h6><%= expense.name %></h6>
        <h6 class="px-3" style="font-size: 13px; text-align: right">$<%= expense.amount %></h6>
      </div>
      <div class="d-flex">
        <%= link_to edit_group_expense_path(@group, expense), class: "btn btn-outline-primary", style: "margin-right: 10px" do %>
            <i class="fa fa-edit"></i>
          <%end%>
        <%= button_to group_expense_path(@group, expense), method: :delete, class: "btn btn-outline-danger" do %>
          <i class="fa fa-trash"></i>
        <%end%>
      </div>
    </div>
    <%end%>
  <%= render 'shared/footer'%>

app/views/expenses/new.html.erb
<%= render 'shared/banner', name: "New #{@group.name} Transaction", amount: nil%>
<% if @expense.errors.any? %>
  <div class="alert alert-danger p-3">
    <h6><%= pluralize(@expense.errors.count, "error") %> prohibited this post from being saved:</h6>

    <ul>
    <% @expense.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="card m-3">
  <div class="card-body">
    <%= form_with model: @expense, url: group_expenses_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
      <%= render 'expenses/form', form: form%>
      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary w-100 mt-2" %>
      </div>
    <%end%>
  </div>
</div>

app/views/groups/_form.html.erb
<div class="mb-3">
  <%= form.label :name, class: "form-label" %><br />
  <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
</div>
<div class="mb-3">
  <%= form.label :icon, class: "form-label" %>
  <%= form.text_field :icon, autofocus: true, autocomplete: "icon", class: "form-control" %>
</div>

app/views/groups/edit.html.erb
<%= render 'shared/banner', name: "Edit #{@group.name}", amount: nil%>
<% if @group.errors.any? %>
  <div class="alert alert-danger p-3">
    <h6><%= pluralize(@group.errors.count, "error") %> prohibited this post from being saved:</h6>

    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="card m-3">
  <div class="card-body">
    <%= form_with model: @group, url: group_path(@group), class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
      <%= render 'groups/form', form: form%>
      <div class="actions">
        <%= form.submit "Update", class: "btn btn-success w-100 mt-2" %>
      </div>
    <%end%>
  </div>
</div>

app/views/groups/index.html.erb
<%= render 'shared/banner', name: "Categories", amount: nil%>
<% if @groups.empty? %>
  <h6 class="p-5 text-danger">You have not added any Category.</h6>
<% end %>
<% @groups.each do |group| %>
    <div class="d-flex justify-content-between align-items-center text-center m-3 p-3 item-container" id="<%= dom_id group %>">
      <%= link_to group_expenses_path(group), class: "d-flex justify-content-between align-items-center text-center text-black", style: "text-decoration: none" do %>
          <div class="d-flex justify-content-between w-100">
            <h5 class="px-5"><%= group.name %></h5><span style="font-size: 13px; float: right; font-weight: bold">$<%= group.total_expenses %></span>
          </div>
      <%end%>
      <div class="d-flex">
        <%= link_to edit_group_path(group), class: "btn btn-outline-primary", style: "margin-right: 10px" do %>
          <i class="fa fa-edit"></i>
        <%end%>
        <%= button_to group_path(group), method: :delete, class: "btn btn-outline-danger" do %>
          <i class="fa fa-trash"></i>
        <%end%>
      </div>
    </div>
<%end%>
<%= render 'shared/footer'%>

app/views/groups/new.html.erb
<%= render 'shared/banner', name: "New Category", amount: nil%>
<% if @group.errors.any? %>
  <div class="alert alert-danger p-3">
    <h6><%= pluralize(@group.errors.count, "error") %> prohibited this post from being saved:</h6>

    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="card m-3">
  <div class="card-body">
    <%= form_with model: @group, url: groups_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
      <%= render 'groups/form', form: form%>
      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary w-100 mt-2" %>
      </div>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4 h-100 main-screen">
        <%= render 'shared/nav'%>
        <%if notice %>
        <p class="notice alert alert-success" role="alert"><%= notice %></p>
        <%end%>
        <%if alert%>
        <p class="alert alert-success" role="alert"><%= alert %></p>
        <%end%>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="d-flex justify-content-between align-items-center p-3">
  <h6><%= name %></h6>
  <h6 class="badge rounded-pill text-bg-success"><%= current_user.name %></h6>
  <%if amount%>
  <h6>Total: $ <%= amount %> </h6>
  <%end%>
</div>

app/views/shared/_footer.html.erb
<footer class="bottom-btns p-2">
  <div class="d-flex justify-content-center text-white">
  <%if controller_name == 'groups'%>
    <% link_path = new_group_path %>
    <% button_name = "Add New Category" %>
  <%else%>
    <% link_path = new_group_expense_path %>
    <% button_name = "Add New Transaction" %>
  <%end%>
  <%= link_to link_path, class: "footer-btn" do%>
    <span class="text-center"> <%= button_name %> </span>
  <%end%>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav>
  <div class="row p-3 text-white">
    <div class="col-4">
      <%if controller_name == 'groups' and action_name == 'index' %>
        <i class="fa fa-bars fa-2x"></i>
      <%elsif controller_name == 'groups' and action_name != 'index' %>
        <%= link_to groups_path do %>
          <i class="fa fa-arrow-left text-white fa-2x"></i>
        <%end%>
      <%elsif controller_name == 'expenses' and action_name == 'index' %>
        <%= link_to groups_path do %>
          <i class="fa fa-arrow-left text-white fa-2x"></i>
        <%end%>
      <%elsif controller_name == 'expenses' and action_name != 'index' %>
        <%= link_to group_expenses_path do %>
          <i class="fa fa-arrow-left text-white fa-2x"></i>
        <%end%>
      <% end %>
    </div>
    <div class="col-4">
      <h2>ENHANCE</h2>
    </div>
    <div class="col-4" style="text-align: right">
    <%if current_user %>
      <%= button_to destroy_user_session_path, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "logout-btn" do%>
          <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i>
      <%end%>
    <%else%>
    <%end%>
    </div>
  </div>
</nav>

app/views/splash/index.html.erb
<% content_for :title, 'Plan Me' %>

<div class="splash-img" >
</div>
<% if current_user %>
  <footer class="bottom-btns p-2">
    <div class="d-flex justify-content-center text-white mb-3">
      <%= link_to groups_path, class: "footer-btn" do%>
        <span class="text-center"> Categories </span>
      <%end%>
    </div>
  </footer>
<% else %>
  <footer class="splash-footer p-2">
    <div class="d-flex justify-content-center text-white mb-3">
      <%= link_to new_user_session_path, class: "footer-btn" do%>
        <span class="text-center"> Login </span>
      <%end%>
    </div>
    <div class="d-flex justify-content-center text-white">
      <%= link_to new_user_registration_path, class: "footer-btn" do%>
        <span class="text-center"> Signup </span>
      <%end%>
    </div>
  </footer>
  <% end %>

app/views/users/splash.html.erb
<% content_for :title, 'Plan Me' %>

<% if current_user %>
  <footer class="bottom-btns p-2">
    <div class="d-flex justify-content-center text-white mb-3">
      <%= link_to groups_path, class: "footer-btn" do%>
        <span class="text-center"> Categories </span>
      <%end%>
    </div>
  </footer>
<% else %>
  <footer class="splash-footer p-2">
    <div class="d-flex justify-content-center text-white mb-3">
      <%= link_to new_user_session_path, class: "footer-btn" do%>
        <span class="text-center"> Login </span>
      <%end%>
    </div>
    <div class="d-flex justify-content-center text-white">
      <%= link_to new_user_registration_path, class: "footer-btn" do%>
        <span class="text-center"> Signup </span>
      <%end%>
    </div>
  </footer>
  <% end %>